### ISSUE TITLE
create new skill page

### ISSUE THREAD

**Issue by SOunit** [SOunit/job_search_app_front#21]
- add a new page to create a new skill
- send data to backend

# sidenote
- backend will create actual skill data and return it back to frontend
- backend fix is needed to have skill table
- skill will be selected when user create a new job(you don't have to add this function in this ticket)

- request url
```
localhost:5000/api/skills
```

<img width="1302" alt="Screen Shot 2022-03-01 at 10 54 43 AM" src="https://user-images.githubusercontent.com/38809138/156231191-f97fe8b2-08d6-4c09-a78b-9b0277c350e7.png">

**Comment by Yuuki915** [comment]
issue solved.
